// src/lib/components/Tabs/TabBar.svelte
<script lang="ts">
  import { onMount, tick } from 'svelte';
  import { tabs, activeTabId, closeTab, saveTab } from '../../stores/fileStore';
  import { get } from 'svelte/store';
  import { X, ChevronLeft, ChevronRight, MoreHorizontal } from 'lucide-svelte';
  import * as DropdownMenu from '$lib/components/ui/dropdown-menu';

  let tabsContainer: HTMLDivElement;

  function handleTabClick(tabId: string) {
    const currentTabs = get(tabs);
    const updatedTabs = currentTabs.map(t => ({ ...t, active: t.id === tabId }));
    tabs.set(updatedTabs);
    activeTabId.set(tabId);
  }

  async function handleTabClose(tabId: string, event: Event) {
    event.stopPropagation();
    event.preventDefault();
    const tab = get(tabs).find(t => t.id === tabId);
    if (tab?.dirty) {
      try {
        await saveTab(tabId);
      } catch (e) {
        console.error('Save failed:', e);
        return;
      }
    }
    closeTab(tabId);
  }

  function handleMiddleClick(tabId: string, event: MouseEvent) {
    if (event.button === 1) handleTabClose(tabId, event);
  }

  // 响应式获取 tabs
  const tabsList = $derived($tabs);

  // 检查是否有溢出需要滚动
  let hasOverflow = $state(false);
  let canScrollLeft = $state(false);
  let canScrollRight = $state(false);

  async function updateScrollState() {
    await tick(); // 等待 DOM 更新
    if (!tabsContainer) return;
    const sl = tabsContainer.scrollLeft;
    const sw = tabsContainer.scrollWidth;
    const cw = tabsContainer.clientWidth;
    canScrollLeft = sl > 0;
    canScrollRight = sl < sw - cw - 1;
    hasOverflow = sw > cw;
  }

  function scrollLeft() {
    if (!tabsContainer) return;
    tabsContainer.scrollBy({ left: -200, behavior: 'smooth' });
    setTimeout(updateScrollState, 250);
  }

  function scrollRight() {
    if (!tabsContainer) return;
    tabsContainer.scrollBy({ left: 200, behavior: 'smooth' });
    setTimeout(updateScrollState, 250);
  }

  function handleScroll() {
    updateScrollState();
  }

  // 监听 tabs 变化，更新滚动状态
  $effect(() => {
    if (tabsList && tabsContainer) {
      updateScrollState();
    }
  });

  // 初始化时也更新一次
  onMount(() => {
    setTimeout(updateScrollState, 100);
  });
</script>

<div class="tab-bar">
  {#if hasOverflow}
    <button class="scroll-btn left visible" onclick={scrollLeft} title="向左滚动">
      <ChevronLeft size={16} strokeWidth={2} />
    </button>
  {/if}

  <div
    class="tabs-container"
    bind:this={tabsContainer}
    onscroll={handleScroll}
  >
    {#each tabsList as tab (tab.id)}
      <div
        class="tab"
        class:active={tab.active}
        class:dirty={tab.dirty}
        onclick={() => handleTabClick(tab.id)}
        onauxclick={(e) => handleMiddleClick(tab.id, e)}
        role="tab"
        tabindex="0"
        aria-selected={tab.active}
        onkeydown={(e) => e.key === 'Enter' && handleTabClick(tab.id)}
      >
        <span class="tab-title">{tab.title}</span>
        {#if tab.dirty}
          <span class="dirty-dot"></span>
        {/if}
        <button
          class="tab-close"
          onclick={(e) => handleTabClose(tab.id, e)}
          tabindex="-1"
          aria-label="Close"
        >
          <X size={14} strokeWidth={2} />
        </button>
      </div>
    {/each}
  </div>

  {#if hasOverflow}
    <button class="scroll-btn right visible" onclick={scrollRight} title="向右滚动">
      <ChevronRight size={16} strokeWidth={2} />
    </button>

    <DropdownMenu.Root>
      <DropdownMenu.Trigger class="more-btn" type="button">
        <MoreHorizontal size={16} strokeWidth={2} />
      </DropdownMenu.Trigger>
      <DropdownMenu.Content>
        {#each tabsList as tab (tab.id)}
          <DropdownMenu.Item onclick={() => handleTabClick(tab.id)}>
            <span class="more-menu-title">{tab.title}</span>
            {#if tab.dirty}
              <span class="dirty-dot"></span>
            {/if}
          </DropdownMenu.Item>
        {/each}
      </DropdownMenu.Content>
    </DropdownMenu.Root>
  {/if}
</div>

<style>
  .tab-bar {
    display: flex;
    background: var(--tab-bg);
    flex-shrink: 0;
    height: 35px;
    overflow: hidden;
    position: relative;
    z-index: 100;
  }

  .tabs-container {
    display: flex;
    overflow-x: auto;
    overflow-y: hidden;
    scrollbar-width: none;
    -ms-overflow-style: none;
    flex: 1;
  }
  .tabs-container::-webkit-scrollbar { height: 0; }

  .scroll-btn {
    width: 28px;
    height: 35px;
    border: none;
    background: var(--tab-bg);
    cursor: pointer;
    display: flex;
    align-items: center;
    justify-content: center;
    color: var(--text-muted);
    flex-shrink: 0;
    border-right: 1px solid var(--tab-border);
    transition: background 0.1s, color 0.1s, opacity 0.15s;
    opacity: 0;
    pointer-events: none;
  }
  .scroll-btn.visible {
    opacity: 1;
    pointer-events: auto;
  }
  .scroll-btn:hover:not(:disabled) {
    background: var(--tab-hover-bg);
    color: var(--text-primary);
  }
  .scroll-btn:disabled {
    opacity: 0.4;
    cursor: default;
  }

  .scroll-btn.left {
    border-left: 1px solid var(--tab-border);
    border-right: none;
  }

  :global(.more-btn) {
    width: 28px;
    height: 35px;
    border: none;
    background: var(--tab-bg);
    cursor: pointer;
    display: flex;
    align-items: center;
    justify-content: center;
    color: var(--text-muted);
    flex-shrink: 0;
    opacity: 1;
    pointer-events: auto;
    border-left: 1px solid var(--tab-border);
    border-right: none;
  }
  :global(.more-btn:hover) {
    background: var(--tab-hover-bg);
    color: var(--text-primary);
  }

  :global(.more-menu-title) {
    flex: 1;
    font-size: 13px;
    color: var(--text-primary);
    white-space: nowrap;
    overflow: hidden;
    text-overflow: ellipsis;
  }

  .tab {
    display: flex;
    align-items: center;
    padding: 0 10px;
    min-width: 80px;
    max-width: 180px;
    height: 35px;
    background: var(--tab-bg);
    border-right: 1px solid var(--tab-border);
    cursor: pointer;
    gap: 6px;
    user-select: none;
    position: relative;
    flex-shrink: 0;
    transition: background 0.08s;
    border-top: 1px solid transparent;
    border-top-width: 1px;
    border-top-style: solid;
    border-top-color: transparent;
    border-bottom: 1px solid transparent;
  }

  .tab:hover {
    background: var(--tab-hover-bg);
  }

  .tab.active {
    background: var(--tab-active-bg);
    border-top: 1px solid var(--tab-activeBorderTop);
    border-bottom: 1px solid var(--tab-activeBorder);
  }

  .tab-title {
    flex: 1;
    font-size: 13px;
    color: var(--text-muted);
    white-space: nowrap;
    overflow: hidden;
    text-overflow: ellipsis;
    order: 0;
  }
  .tab.active .tab-title { color: var(--text-primary); }

  .dirty-dot {
    width: 8px; height: 8px;
    border-radius: 50%;
    background: var(--text-secondary);
    flex-shrink: 0;
    order: 1;
  }

  .tab-close {
    width: 22px; height: 22px;
    border: none;
    background: transparent;
    border-radius: 4px;
    cursor: pointer;
    display: flex;
    align-items: center; justify-content: center;
    color: var(--text-muted);
    flex-shrink: 0;
    transition: background 0.1s, color 0.1s;
    order: 1;
    margin-left: auto;
  }

  .tab:hover .tab-close { color: var(--text-primary); }
  .tab-close:hover {
    background: rgba(255,255,255,0.15);
  }

  /* Dirty state: show dot */
  .tab.dirty .dirty-dot { display: inline-block; }
</style>

// src/components/TabBar.tsx
/**
 * TabBar Component - Editor tabs management
 * Shows file tabs with dirty/saved status indicators
 */
import { useRef, useState, useEffect } from 'react'
import { X, FileText, ChevronLeft, ChevronRight, MoreHorizontal } from 'lucide-react'
import { useEditorStore } from '@/stores'
import { cn } from '@/lib/utils'

function TabBar() {
  const { tabs, activeTabId, setActiveTab, removeTab } = useEditorStore()
  const scrollRef = useRef<HTMLDivElement>(null)
  const tabRefs = useRef<Map<string, HTMLDivElement>>(new Map())
  const [canScrollLeft, setCanScrollLeft] = useState(false)
  const [canScrollRight, setCanScrollRight] = useState(false)
  const [showMoreMenu, setShowMoreMenu] = useState(false)

  const checkScroll = () => {
    if (!scrollRef.current) return
    const { scrollLeft, scrollWidth, clientWidth } = scrollRef.current
    setCanScrollLeft(scrollLeft > 0)
    setCanScrollRight(scrollLeft + clientWidth < scrollWidth - 1)
  }

  useEffect(() => {
    checkScroll()
    const el = scrollRef.current
    if (el) {
      el.addEventListener('scroll', checkScroll)
      window.addEventListener('resize', checkScroll)
    }
    return () => {
      if (el) {
        el.removeEventListener('scroll', checkScroll)
      }
      window.removeEventListener('resize', checkScroll)
    }
  }, [tabs])

  // 当 activeTabId 变化时，自动滚动到活动 tab
  useEffect(() => {
    if (!activeTabId || !scrollRef.current) return
    let rafId: number
    const scrollToActiveTab = () => {
      const tabEl = tabRefs.current.get(activeTabId)
      const scrollEl = scrollRef.current
      if (!tabEl || !scrollEl) return

      const scrollRect = scrollEl.getBoundingClientRect()
      const tabRect = tabEl.getBoundingClientRect()
      
      // 计算 tab 相对于滚动容器的位置
      const tabLeft = tabRect.left - scrollRect.left + scrollEl.scrollLeft
      const tabRight = tabLeft + tabRect.width

      // 如果 tab 不在可视范围内
      if (tabLeft < scrollEl.scrollLeft) {
        scrollEl.scrollTo({ left: tabLeft - 4, behavior: 'smooth' })
      } else if (tabRight > scrollEl.scrollLeft + scrollEl.clientWidth) {
        scrollEl.scrollTo({ left: tabRight - scrollEl.clientWidth + 4, behavior: 'smooth' })
      }
    }

    rafId = requestAnimationFrame(scrollToActiveTab)
    return () => cancelAnimationFrame(rafId)
  }, [activeTabId])

  const scroll = (direction: 'left' | 'right') => {
    if (!scrollRef.current) return
    const scrollAmount = 200
    scrollRef.current.scrollBy({
      left: direction === 'left' ? -scrollAmount : scrollAmount,
      behavior: 'smooth',
    })
  }

  const handleWheel = (e: React.WheelEvent) => {
    if (!scrollRef.current) return
    // 阻止默认垂直滚动，转换为横向滚动
    // 向前滚动（deltaY > 0）→ 向左移动；向后滚动（deltaY < 0）→ 向右移动
    if (Math.abs(e.deltaY) > Math.abs(e.deltaX)) {
      e.preventDefault()
      scrollRef.current.scrollLeft += e.deltaY
    }
  }

  const handleTabClose = (e: React.MouseEvent, tabId: string) => {
    e.stopPropagation()
    removeTab(tabId)
  }

  const scrollToTab = (tabId: string) => {
    const tabEl = tabRefs.current.get(tabId)
    const scrollEl = scrollRef.current
    if (!tabEl || !scrollEl) return

    const scrollRect = scrollEl.getBoundingClientRect()
    const tabRect = tabEl.getBoundingClientRect()

    const tabLeft = tabRect.left - scrollRect.left + scrollEl.scrollLeft
    const tabRight = tabLeft + tabRect.width

    if (tabLeft < scrollEl.scrollLeft) {
      scrollEl.scrollTo({ left: tabLeft - 4, behavior: 'smooth' })
    } else if (tabRight > scrollEl.scrollLeft + scrollEl.clientWidth) {
      scrollEl.scrollTo({ left: tabRight - scrollEl.clientWidth + 4, behavior: 'smooth' })
    }
  }

  const handleTabClick = (tabId: string) => {
    setActiveTab(tabId)
    scrollToTab(tabId)
  }

  if (tabs.length === 0) {
    return (
      <div className="h-10 flex items-center border-b border-[var(--border-color)] bg-[var(--tab-bg)]">
        <span className="px-4 text-sm text-[var(--text-muted)]">No file open</span>
      </div>
    )
  }

  return (
    <div className="h-10 flex items-center border-b border-border bg-[var(--tab-bg)]">
      {/* Left scroll button */}
      <button
        onClick={() => scroll('left')}
        className={cn(
          "h-full px-2 flex items-center justify-center shrink-0",
          "border-r border-[var(--border-color)]",
          canScrollLeft
            ? "text-[var(--text-muted)] hover:bg-[var(--bg-hover)] cursor-pointer"
            : "text-[var(--border-color)] cursor-not-allowed"
        )}
      >
        <ChevronLeft size={16} />
      </button>

      {/* Tabs container */}
      <div
        ref={scrollRef}
        onWheel={handleWheel}
        className="flex-1 flex overflow-x-auto scrollbar-hide"
        style={{
          msOverflowStyle: 'none',
          scrollbarWidth: 'none',
          WebkitOverflowScrolling: 'touch',
        }}
      >
        {tabs.map((tab) => {
          const isActive = tab.id === activeTabId
          return (
            <div
              key={tab.id}
              ref={(el) => {
                if (el) tabRefs.current.set(tab.id, el)
                else tabRefs.current.delete(tab.id)
              }}
              onClick={() => handleTabClick(tab.id)}
              className={cn(
                "group relative flex items-center h-10 px-3 cursor-pointer select-none shrink-0",
                "text-sm border-r border-[var(--tab-border)] min-w-0",
                "transition-colors duration-75",
                isActive
                  ? "bg-[var(--tab-active-bg)] text-[var(--text-primary)] shadow-[inset_0_-1px_0_var(--tab-activeBorderTop)]"
                  : "bg-transparent text-[var(--text-muted)] hover:bg-[var(--tab-hover-bg)] hover:text-[var(--text-secondary)]"
              )}
            >
              {/* Status dot - 编辑过才显示圆点 */}
              {tab.isEdited && (
                tab.isDirty ? (
                  <span className="w-2 h-2 rounded-full bg-red-500 mr-1.5 shrink-0" />
                ) : (
                  <span className="w-2 h-2 rounded-full bg-green-500 mr-1.5 shrink-0" />
                )
              )}

              {/* File icon + name */}
              <FileText size={14} className="shrink-0 mr-1" />
              <span className="truncate max-w-[120px]">{tab.name}</span>

              {/* Close button */}
              <button
                onClick={(e) => handleTabClose(e, tab.id)}
                className={cn(
                  "ml-2 h-4 w-4 flex items-center justify-center rounded-sm shrink-0",
                  "opacity-0 group-hover:opacity-100",
                  "hover:bg-[rgba(255,255,255,0.1)] text-[var(--text-muted)] hover:text-[var(--text-primary)]"
                )}
              >
                <X size={12} />
              </button>
            </div>
          )
        })}
      </div>

      {/* Right scroll button */}
      <button
        onClick={() => scroll('right')}
        className={cn(
          "h-full px-2 flex items-center justify-center shrink-0",
          "border-l border-[var(--border-color)]",
          canScrollRight
            ? "text-[var(--text-muted)] hover:bg-[var(--bg-hover)] cursor-pointer"
            : "text-[var(--border-color)] cursor-not-allowed"
        )}
      >
        <ChevronRight size={16} />
      </button>

      {/* More button */}
      <button
        className="h-full px-2 flex items-center justify-center shrink-0 text-[var(--text-muted)] hover:bg-[var(--bg-hover)] border-l border-[var(--border-color)]"
      >
        <MoreHorizontal size={16} />
      </button>
    </div>
  )
}

export { TabBar }
